services:
  mdm-db:
    image: postgres:15
    environment:
      POSTGRES_DB: mdmdb
      POSTGRES_USER: mdmuser
      POSTGRES_PASSWORD: mdmpass
    ports:
      - "5433:5432"
    networks:
      - mdmnet

  mdm:
    build: ./mdm
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mdm-db:5432/mdmdb
      SPRING_DATASOURCE_USERNAME: mdmuser
      SPRING_DATASOURCE_PASSWORD: mdmpass
    ports:
      - "8081:8080"
    depends_on:
      - mdm-db
    networks:
      - mdmnet

  dem-db:
    image: postgres:15
    environment:
      POSTGRES_DB: demdb
      POSTGRES_USER: demuser
      POSTGRES_PASSWORD: dempass
    ports:
      - "5434:5432"
    networks:
      - mdmnet

  dem:
    build: ./dem
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dem-db:5432/demdb
      SPRING_DATASOURCE_USERNAME: demuser
      SPRING_DATASOURCE_PASSWORD: dempass
      MDM_API_URL: http://mdm:8080
      # JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    ports:
      - "8082:8080"
      - "5005:5005"  # <--- expose debug port
    depends_on:
      - dem-db
      - mdm
    networks:
      - mdmnet


networks:
  mdmnet:
    driver: bridge 